### ISSUE TITLE
☂️ Roadmap for 1.0.0.

### ISSUE THREAD

**Issue by cpojer** [nkzw-tech/fbtee#11]
This is the "umbrella" issue for 1.0, containing a list of "must haves" to make the library feel complete. If you'd like to work on one of these items, please create an issue with the title and I will link it to this issue.

- [ ] Create a <fbt:list> pseudo-component to wrap intlList, @cpojer.
- [ ] "Why fbt is better (than other solutions)" in README.
- [ ] Get rid of duplication between the babel plugin and IntlVariations -> just use one copy of each.
- [ ] Open source locale client side modules used in Athena Crisis and add them to **fbtee**, @cpojer.
- [ ] Examples for Next and app router and others.
- [ ] Improve/update docs folder.
- [ ] Create a new website.
- [ ] Create a new logo.
- [ ] *(optional, may not ship in 1.0) Use real React components instead of fake React Elements.*
- [ ] *(optional, may not ship in 1.0) Fix whitespace behavior to more closely match JSX.*

cc @alexandernanberg, @kayhadrin.

**Comment by tsteckenborn** [comment]
Note: React Router documentation could eventually also be used for Tanstack Start in future, as the errors encountered are -  from my current perception - likely the same.

**Comment by aarjithn** [comment]
Would it be possible to support React 18.2+ instead of 19?

**Comment by cpojer** [comment]
It's unfortunately not possible to support both React 18 and React 19 at the same time. You can most likely patch the `fbtee` package and [change this line](https://github.com/nkzw-tech/fbtee/blob/e35fbe001d6d22878233b291783008d569955dfd/packages/fbtee/src/FbtResult.tsx#L13) from:

```tsx
$$typeof = Symbol.for('react.transitional.element');
```

to:
```tsx
$$typeof = Symbol.for('react.element');
```

and you might need to change the use of `Context` here to `Context.Provider`: https://github.com/nkzw-tech/fbtee/blob/e35fbe001d6d22878233b291783008d569955dfd/packages/fbtee/src/createLocaleContext.tsx#L66

**Comment by cpojer** [comment]
**fbtee 2.0** was just shipped which is significantly more performant (SWC), and modernizes the library quite a bit, see https://github.com/nkzw-tech/fbtee/releases/tag/v2.0.0
